# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-23 06:44
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0003_auto_20180521_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_contribution',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='done',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AddField(
            model_name='player',
            name='income',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='contribution',
            field=otree.db.models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ratio',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
