# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-28 03:07
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0005_group_total_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='individual_share',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
