# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-23 03:57
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0005_player_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='done',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
