# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-23 04:21
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0007_auto_20180522_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='total_contribution',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
