# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-28 03:17
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0007_player_payoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='income',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
