# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 00:37
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0008_auto_20180527_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='transcribed_text2',
            field=otree.db.models.LongStringField(null=True),
        ),
    ]
