# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 02:32
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0009_player_transcribed_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='transcriptionDone',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
