# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 05:43
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0014_auto_20180529_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='baseIncome',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
