# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-31 04:47
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0015_group_baseincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='baseIncome',
            field=otree.db.models.CurrencyField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='income',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
