# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-04 06:44
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0016_auto_20180530_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='authority_multiply',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AddField(
            model_name='group',
            name='random_player',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
