# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 04:20
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0017_auto_20180603_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='auth_appropriate',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
