# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 06:48
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0018_group_auth_appropriate'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='temp',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
