# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-07 02:26
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0019_group_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='spanish',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
