# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-19 05:57
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0022_player_reftext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='refText',
        ),
        migrations.AddField(
            model_name='group',
            name='appropriation',
            field=otree.db.models.CurrencyField(null=True),
        ),
    ]
