# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-19 06:01
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0023_auto_20180618_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='refText',
            field=otree.db.models.LongStringField(null=True),
        ),
    ]
