# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 00:51
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('real_effort', '0024_player_reftext'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='audit',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='appropriation',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='income',
            field=otree.db.models.IntegerField(null=True),
        ),
    ]
